---

Local:
  menu: Local
  title: Local Network
  remark: Devices that are behind your router and / or modem

  NetworkAnalyzer:
    menu: Network Analyzer
    title: Network Analyzer
    remark: This is the virtual machine checking network latency
    host: localhost
