---

DNS:
  menu: DNS
  title: Major DNS Servers

  Cloudflare1:
    menu: Cloudflare
    title: Primary Cloudflare DNS Server (1.1.1.1)
    host: 1.1.1.1

  GoogleDNS1:
    menu: Google
    title: Primary Google DNS Server (8.8.8.8)
    host: 8.8.8.8

  OpenDNS:
    menu: OpenDNS
    title: Primary OpenDNS DNS Server (208.67.222.222)
    host: 208.67.222.222

  Quad9:
    menu: Quad9
    title: Primary Quad9 DNS Server (9.9.9.9)
    host: 9.9.9.9
